version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mongodb
      - postgresql

  mongodb:
    image: mongo

  postgresql:
    image: postgres:latest
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apolicy_db
    ports:
      - 5432:5432